def initialize_data(last_number_games):
    return {
        'date' : [],
        'rest_days_prior': [],
        'location': [],
        'minutes_played': [],
        f'minutes_played_last{last_number_games}': [],
        'started' : [],
        'player_ppg': [],
        f'player_ppg_last{last_number_games}': [],
        'player_field_goals' : [],
        f'player_field_goals_last{last_number_games}': [],
        'player_field_goals_attempted' : [],
        f'player_field_goals_attempted_last{last_number_games}': [],

        'player_field_goal_percentage' : [],
        f'player_field_goal_percentage_last{last_number_games}': [],
        'player_three_pointers' : [],
        f'player_three_pointers_last{last_number_games}': [],
        'player_three_pointers_attempted' : [],
        f'player_three_pointers_attempted_last{last_number_games}': [],
        'player_three_pointers_percentage' : [],
        f'player_three_pointers_percentage_last{last_number_games}': [],
        'player_free_throws' : [],
        f'player_free_throws_last{last_number_games}': [],
        'player_free_throws_attempted' : [],
        f'player_free_throws_attempted_last{last_number_games}': [],
        'player_free_throw_percentage' : [],
        f'player_free_throw_percentage_last{last_number_games}': [],
        'player_total_rebounds' : [],
        f'player_total_rebounds_last{last_number_games}' : [],
        'player_assists' : [],
        f'player_assists_last{last_number_games}' : [],
        'player_steals' : [],
        f'player_steals_last{last_number_games}' : [],
        'player_blocks' : [],
        f'player_blocks_last{last_number_games}' : [],
        'player_turnovers' : [],
        f'player_turnovers_last{last_number_games}' : [],
        'player_game_score' : [],
        f'player_game_score_last{last_number_games}': [],
        'player_personal_fouls' : [],
        f'player_personal_fouls_last{last_number_games}': [],
        'player_plus_minus' : [],
        f'player_plus_minus_last{last_number_games}': [],
        'player_true_shooting_percentage' : [],
        f'player_true_shooting_percentage_last{last_number_games}': [],
        'player_effective_field_goal_percentage' : [],
        f'player_effective_field_goal_percentage_last{last_number_games}': [],
        'player_total_rebound_percentage' : [],
        f'player_total_rebound_percentage_last{last_number_games}' : [],
        'player_assist_percentage' : [],
        f'player_assist_percentage_last{last_number_games}' : [],
        'player_steal_percentage' : [],
        f'player_steal_percentage_last{last_number_games}' : [],
        'player_block_percentage': [],
        f'player_block_percentage_last{last_number_games}' : [],
        'player_turnover_percentage' : [],
        f'player_turnover_percentage_last{last_number_games}' : [],
        'player_offensive_rating' : [],
        f'player_offensive_rating_last{last_number_games}' : [],
        'player_defensive_rating' : [],
        f'player_defensive_rating_last{last_number_games}' : [],
        'player_usage_rate' : [],
        f'player_usage_rate_last{last_number_games}': [],
        
        'team_offensive_rating': [],
        f'team_offensive_rating_last{last_number_games}' : [],
        'team_defensive_rating': [],
        f'team_defensive_rating_last{last_number_games}': [],
        'team_pace': [],
        f'team_pace_last{last_number_games}': [],
        'team_free_throw_attempt_rate' : [],
        f'team_free_throw_attempt_rate_last{last_number_games}': [],
        'team_three_point_attempt_rate' : [],
        f'team_three_point_attempt_rate_last{last_number_games}': [],
        'team_true_shooting_percentage' : [],
        f'team_true_shooting_percentage_last{last_number_games}': [],
        'team_total_reboound_percentage' : [],
        f'team_total_reboound_percentage_last{last_number_games}': [],
        'team_assist_percentage' : [],
        f'team_assist_percentage_last{last_number_games}': [],
        'team_steal_percentage' : [],
        f'team_steal_percentage_last{last_number_games}': [],
        'team_offensive_effective_field_goal_percentage' : [],
        f'team_offensive_effective_field_goal_percentage_last{last_number_games}': [],
        'team_offensive_free_throws_per_field_goal_attempt_percentage' : [],
        f'team_offensive_free_throws_per_field_goal_attempt_percentage_last{last_number_games}': [],
        'team_defensive_free_throws_per_field_goal_attempt_percentage' : [],
        f'team_defensive_free_throws_per_field_goal_attempt_percentage_last{last_number_games}': [],
        'team_defensive_effective_field_goal_percentage' : [],
        f'team_defensive_effective_field_goal_percentage_last{last_number_games}': [],
        'opponent': [],
        'opponent_defensive_rating': [],
        f'opponent_defensive_rating_last{last_number_games}': [],
        'opponent_pace': [],
        f'opponent_pace_last{last_number_games}': [],
        'opponent_defensive_effective_field_goal_percentage' : [],
        f'opponent_defensive_effective_field_goal_percentage_last{last_number_games}': [],
        'opponent_defensive_turnover_percentage' : [],
        f'opponent_defensive_turnover_percentage_last{last_number_games}': [],
        'opponent_defensive_rebound_percentage' : [],
        f'opponent_defensive_rebound_percentage_last{last_number_games}': [],
        'opponent_defensive_free_throws_per_field_goal_attempt_percentage' : [],
        f'opponent_defensive_free_throws_per_field_goal_attempt_percentage_last{last_number_games}': [],
        'points_against_opponent': [],
        'assists_against_opponent' : [],
        'blocks_against_opponent' : [],
        'steals_against_opponent' : [],
        'rebounds_against_opponent' : [],
        'game_score_against_opponent' : [],
        f'target': []
    }
