# Generated by Django 5.1.4 on 2025-01-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_estimator', '0002_playerseason_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='name',
        ),
    ]
