# Generated by Django 5.1.4 on 2025-02-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_estimator', '0003_remove_playerseason_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='gamelogplayeradvancedstats',
            name='season',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='gamelogplayergeneralstats',
            name='season',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='teamgamelogadvancedstats',
            name='season',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='teamgameloggeneralstats',
            name='season',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='teamschedule',
            name='season',
            field=models.IntegerField(default=2025),
        ),
    ]
